### ISSUE TITLE
not saving ID

### ISSUE THREAD

**Issue by bbeckann** [zRxnx/zrx_uniqueid#1]
Well, when starting the script it is working normally, but when relogging I noticed that it is not missing the ID, fixing the id.

![image](https://github.com/zRxnx/zrx_uniqueid/assets/95275692/1d828a81-b577-49a5-a20e-7aaf995f260e)
and another error would be when trying to change the ID to 1 it gave me these errors.

![image](https://github.com/zRxnx/zrx_uniqueid/assets/95275692/7b09c4f3-8866-4fb3-a5e0-118738be8872)
![image](https://github.com/zRxnx/zrx_uniqueid/assets/95275692/461445be-bed5-4e48-bfba-0a3c8538dc3c)

**Comment by zRxnx** [comment]
What do you mean by "relogging"

**Comment by bbeckann** [comment]
enter the server again the server id changes automatically , it is not fixing the serve id

**Comment by zRxnx** [comment]
Well, the server id always changes.

**Comment by zRxnx** [comment]
Use latest version
