### ISSUE TITLE
error menu 

### ISSUE THREAD

**Issue by mbeckann** [zRxnx/zrx_uniqueid#2]
^1SCRIPT ERROR: @zrx_uniqueid/client/functions.lua:34: attempt to index a nil value (field ‘Menu’)^7

```
    CORE.Client.CreateMenu({
        id = 'zrx_uniqueid:menu:main',
        title = Strings.menu_main,
    }, MENU, Config.Menu.type ~= 'menu', Config.Menu.postition)
end
```

**Comment by zRxnx** [comment]
doesnt make sense, do a cleaninstall of the script

**Comment by mbeckann** [comment]
I reinstalled the script and still receive the same error.

**Comment by mbeckann** [comment]
```
Config.CheckForUpdates = true --| Check for updates?
Config.IconColor = 'rgba(173, 216, 230, 1)' --| rgba format
Config.Command = 'manageuid' --| Command to open manage menu
Config.Key = 'C' --| Keymapping
Config.Menu  = {
    type = 'menu'
}
```


able to solve the problem, you forgot to define it in your config as shown above

before
`Config = {}

Config.CheckForUpdates = true --| Check for updates?
Config.IconColor = 'rgba(173, 216, 230, 1)' --| rgba format
Config.Command = 'manageuid' --| Command to open manage menu
Config.Key = 'F12' --| Keymapping

Config.Manage = {
    groups = {
        admin = true
    },

    identifiers = { --| discord, license or discord
        [811603268898652161] = true
    }
}

--| Place here your punish actions
Config.PunishPlayer = function(player, reason)
    if not IsDuplicityVersion() then return end
    if Webhook.Links.punish:len() > 0 then
        local message = ([[
            The player got punished

            Reason: **%s**
        ]]):format(reason)

        CORE.Server.DiscordLog(player, 'PUNISH', message, Webhook.Links.punish)
    end

    DropPlayer(player, reason)
end`

**Comment by zRxnx** [comment]
thanks fixed
