### ISSUE TITLE
error when i try open manageuid

### ISSUE THREAD

**Issue by vlad264** [zRxnx/zrx_uniqueid#4]
![image](https://github.com/zRxnx/zrx_uniqueid/assets/118624858/92028158-31b8-42cc-86f4-b16a7fc70898)
and i also have question how can I add an ID to a player that is not in manageuid

**Comment by vlad264** [comment]
![image](https://github.com/zRxnx/zrx_uniqueid/assets/118624858/c289c45c-93ba-471c-b655-57680fce7f2e)

**Comment by vlad264** [comment]
![image](https://github.com/zRxnx/zrx_uniqueid/assets/118624858/4348f419-daff-4b92-973f-6e94bb43397b)

**Comment by zRxnx** [comment]
When does this happen?

I cant reproduce that on my end

**Comment by zRxnx** [comment]
I uploaded a new version of uniqueid, this could fix this

**Comment by vlad264** [comment]
ok, I'll update and check everything now

**Comment by vlad264** [comment]
Everything worked fine, but can you tell me the question of how to link this id to other scripts?

**Comment by zRxnx** [comment]
With the export GetUID you can get the UID from an ID.
Example:
`print(exports.zrx_uniqueid:GetUID(MY_SERVERID))`

With the export GetID you can get the ID from an UID.
Example:
`print(exports.zrx_uniqueid:GetID(MY_UID))`

With the export ChangeUID you can change the UID.
Example:
`exports.zrx_uniqueid:ChangeUI(OLD_UID, NEW_UID)`

**Comment by vlad264** [comment]
![image](https://github.com/zRxnx/zrx_uniqueid/assets/118624858/c766cea8-f125-48ee-ab42-66139c80c953)
that is, here I have to change xplayer to exports.zrx_uniqueid:ChangeUI(OLD_UID, NEW_UID)
and if I can contact you on discord for a consultation it would be nice if you don’t mind

**Comment by vlad264** [comment]
![image](https://github.com/zRxnx/zrx_uniqueid/assets/118624858/ee83e742-a93a-4ae8-8604-9fa37c80d681)
![image](https://github.com/zRxnx/zrx_uniqueid/assets/118624858/bb731206-2cb3-4640-ad44-c15f0409dae3)

**Comment by zRxnx** [comment]
I will do a docs page soon, should be all clear then
