### ISSUE TITLE
error

### ISSUE THREAD

**Issue by gaborelo** [zRxnx/zrx_uniqueid#5]
![image](https://github.com/zRxnx/zrx_uniqueid/assets/97791495/658ed83c-c88c-49dd-be83-3b673bd5f925)

**Comment by gaborelo** [comment]
![image](https://github.com/zRxnx/zrx_uniqueid/assets/97791495/a7250934-a4b6-4239-be3f-2cf97616e321)

**Comment by zRxnx** [comment]
When does this happen?

**Comment by vlad264** [comment]
we have same issue after restarts or new players when you press f12 or /manageuids we have this error

**Comment by vlad264** [comment]
![image](https://github.com/zRxnx/zrx_uniqueid/assets/118624858/1c52e3eb-2d75-4e67-907d-c45c3ba3532c)

**Comment by zRxnx** [comment]
If you still have this join the dc xd

**Comment by zRxnx** [comment]
8
